### ISSUE TITLE
Update monitor.json with latest list of CT Log servers

### ISSUE THREAD

**Issue by shubham8agar** [SSLMate/certspotter#65]
Default list of monitor.json at https://loglist.certspotter.org/monitor.json needs to be updated with updated list at https://www.gstatic.com/ct/log_list/v3/log_list.json

Reference: https://github.com/google/certificate-transparency-community-site/blob/master/docs/google/known-logs.md

**Comment by AGWA** [comment]
Hi @shubham8agar,

https://www.gstatic.com/ct/log_list/v3/log_list.json lists logs which are retired or contain exclusively expired certificates.  Since these logs are not appropriate for monitoring, they are excluded from https://loglist.certspotter.org/monitor.json 

We have monitoring and automation to ensure that https://loglist.certspotter.org/monitor.json lists all logs which are considered qualified or usable by Chrome or Apple and which contain unexpired certificates.
